# Generated by Django 3.0.7 on 2020-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('has_3g', models.BooleanField()),
                ('has_lte', models.BooleanField()),
                ('sims_count', models.IntegerField()),
                ('operational_system', models.TextField()),
                ('ram', models.IntegerField()),
                ('device_memory', models.IntegerField()),
                ('processor', models.TextField()),
                ('has_fm', models.BooleanField()),
                ('has_bluetooth', models.BooleanField()),
                ('has_gps', models.BooleanField()),
            ],
        ),
    ]
