# Generated by Django 2.2.10 on 2020-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200619_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_scope_id',
            field=models.IntegerField(default=0, verbose_name='ID основного тэга'),
        ),
    ]
