# Generated by Django 2.2.10 on 2020-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_main_scope_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_scope_id',
            field=models.IntegerField(verbose_name='ID основного тэга'),
        ),
    ]
