# Generated by Django 2.2.10 on 2020-06-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200625_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_scope_id',
        ),
    ]
